apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: load-target-keda-gcp-rps
  namespace: load-test
spec:
  scaleTargetRef:
    name: load-target
  minReplicaCount: 15
  maxReplicaCount: 100

  pollingInterval: 15
  cooldownPeriod: 60

  triggers:
    - type: gcp-stackdriver
      metadata:
        projectId: MY_PROJECT_ID
        filter: >
          metric.type="custom.googleapis.com/testapi/request_count"
          AND resource.type="global"
          AND metric.label.endpoint="work"
        # 平常: 15podで1000RPS → 1podあたり約70RPS目標
        targetValue: "70"
        activationTargetValue: "1"

        # ひな形（あとで調整OK）
        alignmentPeriodSeconds: "60"
        alignmentAligner: rate
        alignmentReducer: sum
        filterDuration: "2"
