apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keda-operator-secret-access
  namespace: keda
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keda-operator-secret-access
  namespace: keda
subjects:
  - kind: ServiceAccount
    name: keda-operator
    namespace: keda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-operator-secret-access
