apiVersion: v1
kind: Namespace
metadata:
  name: load-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-target
  namespace: load-test
  # Workload Identity を使うなら紐付け（不要なら annotations 行ごと削除でOK）
  annotations:
    iam.gke.io/gcp-service-account: load-target-gsa@MY_PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-target
  namespace: load-test
  labels:
    app: load-target
spec:
  replicas: 15
  selector:
    matchLabels:
      app: load-target
  template:
    metadata:
      labels:
        app: load-target
    spec:
      serviceAccountName: load-target
      containers:
        - name: app
          image: asia-northeast1-docker.pkg.dev/MY_PROJECT_ID/my-repo/load-target:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            # Cloud Monitoring へメトリクス送信ON（不要なら3つとも削除OK）
            - name: GCP_PROJECT
              value: "MY_PROJECT_ID"
            - name: METRIC_TYPE
              value: "custom.googleapis.com/testapi/request_count"
            - name: METRIC_PUSH_INTERVAL_SEC
              value: "10"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: load-target
  namespace: load-test
spec:
  selector:
    app: load-target
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
