apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: metrics-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:metrics-server
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - nodes/stats
      - nodes/metrics
      - services
      - endpoints
      - events
      - configmaps         # ← これがないと今回のエラーになる
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:metrics-server
roleRef:
  kind: ClusterRole
  name: system:metrics-server
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: metrics-server
